### ISSUE TITLE
Error if user types in wrong password when logging

### ISSUE THREAD

**Issue by travisricks** [CC-Cherry-Garcia/oneMoonReactNative#16]

**Comment by travisricks** [comment]
<img width="611" alt="Screen Shot 2020-03-12 at 4 02 28 PM" src="https://user-images.githubusercontent.com/289841/76495762-e2ad0900-647a-11ea-91cf-0e4421d7777e.png">

If the user types in the wrong password, they get this screen. They should get a feedback message instead.

**Comment by masumomo** [comment]
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/CommonErrors.html

When login failed, Cognito returns these information as JSON object.
I guess we can use 'message' value as err message and go back to login page again. I can do it, but I want to do it after login page is fixed.
